# Generated by Django 4.2.3 on 2023-07-23 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dados', '0002_delete_jogador'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fatores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heroi', models.CharField(max_length=50)),
                ('faseAtual', models.IntegerField()),
                ('fatorCura', models.FloatField()),
                ('fatorXP', models.FloatField()),
                ('fatorEvolucao', models.FloatField()),
                ('playerAtacando', models.BooleanField(default=False)),
                ('inimigoAtacando', models.BooleanField(default=False)),
                ('playerCurando', models.BooleanField(default=False)),
                ('inimigoCurando', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Inimigos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('fase', models.IntegerField()),
                ('vida', models.FloatField()),
                ('vidaMaxima', models.IntegerField()),
                ('experiencia', models.IntegerField()),
                ('ataqueMaximo', models.IntegerField()),
                ('tempoCura', models.IntegerField()),
                ('urlNormal', models.CharField(max_length=250)),
                ('urlAtacando', models.CharField(max_length=250)),
                ('urlCurando', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Jogador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nivel', models.IntegerField()),
                ('vida', models.FloatField()),
                ('vidaMaxima', models.IntegerField()),
                ('ataqueMaximo', models.IntegerField()),
                ('xp', models.IntegerField()),
                ('proximoNivel', models.IntegerField()),
                ('chanceCritico', models.FloatField()),
                ('urlNormal', models.CharField(max_length=250)),
                ('urlAtacando', models.CharField(max_length=250)),
                ('urlCurando', models.CharField(max_length=250)),
                ('urlApanhando', models.CharField(max_length=250)),
                ('urlCritico', models.CharField(max_length=250)),
            ],
        ),
    ]
