# Generated by Django 4.2.3 on 2023-07-23 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dados', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inimigos',
            name='tempoAtaque',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
